### ISSUE TITLE
Is this repo abandoned?  If so, please mark your Jenkins plugin as up for adoption.

### ISSUE THREAD

**Issue by KnownSubset** [jnewc/github-coverage-reporter#6]
This seems like a valuable plugin, but it is unusable in its current state due a bad [annotation](https://github.com/jnewc/github-coverage-reporter/blob/e44640b8df8b52086773fe515497001311eabd4d/src/main/java/io/jenkins/plugins/gcr/models/ComparisonOption.java#L42).

Myself, or others, would like to fix it up and use it. The repo's owner should solicit co-maintainers or mark the plugin as being abandoned through [Jenkin's wiki](https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin#AdoptaPlugin-HowcanImarkapluginforadoption?).

**Comment by jnewc** [comment]
This is not abandoned, I just haven't had time to add anything recently.

I will be doing a release before the end of January. If you submit a PR for any issues before then, I would be happy to release earlier than that.
